#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'network-on-chip'
#
# Generated by Vivado on Sat Apr 18 23:19:58 +0530 2026 (Modified path resolution - Krishang)
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# Usage (from the repo root):
#   source create_project.tcl
#   source create_project.tcl -tclargs --project_name my_noc
#
# All source paths are resolved relative to the directory containing this
# script, so the project can be recreated on any machine regardless of where
# the repository is cloned.
#*****************************************************************************************

# ---------------------------------------------------------------------------
# Locate the script and treat its directory as the repository root
# ---------------------------------------------------------------------------
set script_path [file normalize [info script]]
set repo_root   [file dirname $script_path]

# Allow the user to override the root via --origin_dir
set origin_dir $repo_root
if { [info exists ::origin_dir_loc] } {
    set origin_dir [file normalize $::origin_dir_loc]
}

# ---------------------------------------------------------------------------
# Project name (overridable via --project_name)
# ---------------------------------------------------------------------------
set _xil_proj_name_ "project_8"
if { [info exists ::user_project_name] } {
    set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "create_project.tcl"

proc print_help {} {
    variable script_file
    puts "\nDescription:"
    puts "Recreate the Network-on-Chip Vivado project from this script."
    puts "All source paths are relative to the repository root.\n"
    puts "Syntax:"
    puts "$script_file"
    puts "$script_file -tclargs \[--origin_dir <path>\]"
    puts "$script_file -tclargs \[--project_name <name>\]"
    puts "$script_file -tclargs \[--help\]\n"
    puts "Usage:"
    puts "Name                   Description"
    puts "-------------------------------------------------------------------------"
    puts "\[--origin_dir <path>\]  Override the repository root path."
    puts "                       Defaults to the directory containing this script.\n"
    puts "\[--project_name <name>\] Create project with the specified name."
    puts "                       Default: project_8\n"
    puts "\[--help\]               Print this help message."
    puts "-------------------------------------------------------------------------\n"
    exit 0
}

if { $::argc > 0 } {
    for {set i 0} {$i < $::argc} {incr i} {
        set option [string trim [lindex $::argv $i]]
        switch -regexp -- $option {
            "--origin_dir"   { incr i; set origin_dir [file normalize [lindex $::argv $i]] }
            "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
            "--help"         { print_help }
            default {
                if { [regexp {^-} $option] } {
                    puts "ERROR: Unknown option '$option'. Use '$script_file -tclargs --help' for usage.\n"
                    return 1
                }
            }
        }
    }
}

# ---------------------------------------------------------------------------
# Convenience: build an absolute path from a repo-relative path
# ---------------------------------------------------------------------------
proc repo_path {args} {
    global origin_dir
    return [file normalize [file join $origin_dir {*}$args]]
}

# ---------------------------------------------------------------------------
# Create project
# ---------------------------------------------------------------------------
create_project ${_xil_proj_name_} [file join $origin_dir ${_xil_proj_name_}] -part xc7a100tcsg324-1

set proj_dir [get_property directory [current_project]]

# ---------------------------------------------------------------------------
# Project properties
# ---------------------------------------------------------------------------
set obj [current_project]
set_property -name "board_part"                      -value "digilentinc.com:nexys-a7-100t:part0:1.3" -objects $obj
set_property -name "default_lib"                     -value "xil_defaultlib"  -objects $obj
set_property -name "enable_resource_estimation"      -value "0"               -objects $obj
set_property -name "enable_vhdl_2008"                -value "1"               -objects $obj
set_property -name "ip_cache_permissions"            -value "read write"      -objects $obj
set_property -name "ip_output_repo"                  -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1"              -objects $obj
set_property -name "platform.board_id"               -value "nexys-a7-100t"   -objects $obj
set_property -name "revised_directory_structure"     -value "1"               -objects $obj
set_property -name "sim.central_dir"                 -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts"      -value "1"               -objects $obj
set_property -name "sim_compile_state"               -value "1"               -objects $obj
set_property -name "use_inline_hdl_ip"               -value "1"               -objects $obj

# ---------------------------------------------------------------------------
# sources_1 fileset
# ---------------------------------------------------------------------------
if {[string equal [get_filesets -quiet sources_1] ""]} {
    create_fileset -srcset sources_1
}

set obj [get_filesets sources_1]

set src_files [list \
    [repo_path rtl input_buffer_fifo.v]              \
    [repo_path rtl network_interface.v]              \
    [repo_path rtl uart uart_rx.v]                   \
    [repo_path rtl uart uart_tx.v]                   \
    [repo_path rtl xy_router.v]                      \
    [repo_path rtl crossbar_switch.sv]               \
    [repo_path rtl router_5port.sv]                  \
    [repo_path rtl switch_allocator.sv]              \
    [repo_path rtl top_noc_fabric.sv]                \
    [repo_path rtl uart uart_cmd_parser.sv]          \
    [repo_path rtl uart uart_resp_formatter.sv]      \
    [repo_path fpga top top_fpga_uart_stream_noc.sv] \
]

foreach f $src_files {
    import_files -fileset sources_1 $f
}

# File-type overrides (SystemVerilog)
foreach sv_file {
    rtl/crossbar_switch.sv
    rtl/router_5port.sv
    rtl/switch_allocator.sv
    rtl/top_noc_fabric.sv
    uart/uart_cmd_parser.sv
    uart/uart_resp_formatter.sv
    top/top_fpga_uart_stream_noc.sv
} {
    set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$sv_file"]]
    if { $file_obj ne "" } {
        set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
    }
}

set_property -name "dataflow_viewer_settings" -value "min_width=16"              -objects [get_filesets sources_1]
set_property -name "top"                      -value "top_fpga_uart_stream_noc"  -objects [get_filesets sources_1]

# ---------------------------------------------------------------------------
# constrs_1 fileset
# ---------------------------------------------------------------------------
if {[string equal [get_filesets -quiet constrs_1] ""]} {
    create_fileset -constrset constrs_1
}

set xdc_file [repo_path fpga constraints constraints.xdc]
import_files -fileset constrs_1 $xdc_file

set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*constraints.xdc"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# ---------------------------------------------------------------------------
# sim_1 fileset
# ---------------------------------------------------------------------------
if {[string equal [get_filesets -quiet sim_1] ""]} {
    create_fileset -simset sim_1
}

set obj [get_filesets sim_1]

set sim_files [list \
    [repo_path rtl sim tb_input_buffer_fifo.v]  \
    [repo_path rtl sim tb_uart_bridge.sv]        \
    [repo_path rtl sim tb_router_5port.sv]       \
    [repo_path rtl sim tb_xy_router.v]           \
    [repo_path rtl sim tb_uart_standalone.v]     \
    [repo_path rtl sim tb_top_noc.sv]            \
    [repo_path rtl sim tb_crossbar_switch.sv]    \
    [repo_path rtl sim tb_switch_allocator.sv]   \
    [repo_path rtl sim tb_network_interface.v]   \
]

foreach f $sim_files {
    import_files -fileset sim_1 $f
}

# File-type overrides for sim (SystemVerilog)
foreach sv_file {
    sim/tb_uart_bridge.sv
    sim/tb_router_5port.sv
    sim/tb_top_noc.sv
    sim/tb_crossbar_switch.sv
    sim/tb_switch_allocator.sv
} {
    set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$sv_file"]]
    if { $file_obj ne "" } {
        set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
    }
}

set_property -name "sim_wrapper_top" -value "1"                        -objects [get_filesets sim_1]
set_property -name "top"             -value "top_fpga_uart_stream_noc" -objects [get_filesets sim_1]
set_property -name "top_lib"         -value "xil_defaultlib"           -objects [get_filesets sim_1]

# ---------------------------------------------------------------------------
# Synthesis run
# ---------------------------------------------------------------------------
set idrFlowPropertiesConstraints ""
catch {
    set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
    set_param runs.disableIDRFlowPropertyConstraints 1
}

if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 \
        -flow {Vivado Synthesis 2025} \
        -strategy "Vivado Synthesis Defaults" \
        -report_strategy {No Reports} \
        -constrset constrs_1
} else {
    set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
    set_property flow     "Vivado Synthesis 2025"     [get_runs synth_1]
}

set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj

if { [string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] ""] } {
    create_report_config \
        -report_name synth_1_synth_report_utilization_0 \
        -report_type report_utilization:1.0 \
        -steps synth_design \
        -runs synth_1
}

set_property -name "auto_incremental_checkpoint" -value "1"                        -objects [get_runs synth_1]
set_property -name "strategy"                    -value "Vivado Synthesis Defaults" -objects [get_runs synth_1]

current_run -synthesis [get_runs synth_1]

# ---------------------------------------------------------------------------
# Implementation run
# ---------------------------------------------------------------------------
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 \
        -flow {Vivado Implementation 2025} \
        -strategy "Vivado Implementation Defaults" \
        -report_strategy {No Reports} \
        -constrset constrs_1 \
        -parent_run synth_1
} else {
    set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
    set_property flow     "Vivado Implementation 2025"     [get_runs impl_1]
}

set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj

# Report configs
foreach {rname rtype rstep} {
    impl_1_init_report_timing_summary_0          report_timing_summary:1.0  init_design
    impl_1_opt_report_drc_0                      report_drc:1.0             opt_design
    impl_1_opt_report_timing_summary_0           report_timing_summary:1.0  opt_design
    impl_1_power_opt_report_timing_summary_0     report_timing_summary:1.0  power_opt_design
    impl_1_place_report_io_0                     report_io:1.0              place_design
    impl_1_place_report_utilization_0            report_utilization:1.0     place_design
    impl_1_place_report_control_sets_0           report_control_sets:1.0    place_design
    impl_1_place_report_incremental_reuse_0      report_incremental_reuse:1.0 place_design
    impl_1_place_report_incremental_reuse_1      report_incremental_reuse:1.0 place_design
    impl_1_place_report_timing_summary_0         report_timing_summary:1.0  place_design
    impl_1_post_place_power_opt_report_timing_summary_0 report_timing_summary:1.0 post_place_power_opt_design
    impl_1_phys_opt_report_timing_summary_0      report_timing_summary:1.0  phys_opt_design
    impl_1_route_report_drc_0                    report_drc:1.0             route_design
    impl_1_route_report_methodology_0            report_methodology:1.0     route_design
    impl_1_route_report_power_0                  report_power:1.0           route_design
    impl_1_route_report_route_status_0           report_route_status:1.0    route_design
    impl_1_route_report_timing_summary_0         report_timing_summary:1.0  route_design
    impl_1_route_report_incremental_reuse_0      report_incremental_reuse:1.0 route_design
    impl_1_route_report_clock_utilization_0      report_clock_utilization:1.0 route_design
    impl_1_route_report_bus_skew_0               report_bus_skew:1.1        route_design
    impl_1_post_route_phys_opt_report_timing_summary_0 report_timing_summary:1.0 post_route_phys_opt_design
    impl_1_post_route_phys_opt_report_bus_skew_0 report_bus_skew:1.1       post_route_phys_opt_design
} {
    if { [string equal [get_report_configs -of_objects [get_runs impl_1] $rname] ""] } {
        create_report_config \
            -report_name $rname \
            -report_type $rtype \
            -steps       $rstep \
            -runs        impl_1
    }
}

set_property -name "strategy"                                -value "Vivado Implementation Defaults" -objects [get_runs impl_1]
set_property -name "steps.write_bitstream.args.readback_file" -value "0"                            -objects [get_runs impl_1]
set_property -name "steps.write_bitstream.args.verbose"       -value "0"                            -objects [get_runs impl_1]

current_run -implementation [get_runs impl_1]

catch {
    if { $idrFlowPropertiesConstraints ne {} } {
        set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
    }
}

# ---------------------------------------------------------------------------
# Dashboard gadgets
# ---------------------------------------------------------------------------
foreach {gname gtype} {
    drc_1         drc
    methodology_1 methodology
    power_1       power
    timing_1      timing
    utilization_1 utilization
    utilization_2 utilization
} {
    if {[string equal [get_dashboard_gadgets [list $gname]] ""]} {
        create_dashboard_gadget -name $gname -type $gtype
    }
}

set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0"         -objects [get_dashboard_gadgets [list "drc_1"]]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects [get_dashboard_gadgets [list "methodology_1"]]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0"       -objects [get_dashboard_gadgets [list "power_1"]]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects [get_dashboard_gadgets [list "timing_1"]]

set obj [get_dashboard_gadgets [list "utilization_1"]]
set_property -name "reports"  -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design"  -objects $obj
set_property -name "run.type" -value "synthesis"     -objects $obj

set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects [get_dashboard_gadgets [list "utilization_2"]]

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1}       -row 1 -col 0
move_dashboard_gadget -name {drc_1}         -row 2 -col 0
move_dashboard_gadget -name {timing_1}      -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1

puts "INFO: Project created: ${_xil_proj_name_}"
puts "INFO: Repository root used: ${origin_dir}"